/**
 * Onboarding Task Templates
 * Defines all tasks for the 21-day onboarding journey
 * Each day has required and optional tasks with points
 */

export interface OnboardingTaskTemplate {
  taskId: string;
  taskType: string;
  title: string;
  description: string;
  requiredForDay: boolean;
  points: number;
  actionUrl?: string;
  estimatedMinutes?: number;
  videoUrl?: string;
}

export const ONBOARDING_TEMPLATES: Record<number, OnboardingTaskTemplate[]> = {
  1: [
    {
      taskId: 'view-client-overview',
      taskType: 'exploration',
      title: 'Explore Client Management',
      description: 'Take a tour of the Clients page to understand how to manage your client relationships',
      requiredForDay: true,
      points: 50,
      actionUrl: '/clients',
      estimatedMinutes: 5,
    },
    {
      taskId: 'complete-profile',
      taskType: 'profile',
      title: 'Complete Your Profile',
      description: 'Add your personal details and preferences to personalize your experience',
      requiredForDay: true,
      points: 100,
      actionUrl: '/settings/profile',
      estimatedMinutes: 10,
    },
    {
      taskId: 'explore-dashboard',
      taskType: 'exploration',
      title: 'Explore Your Dashboard',
      description: 'Get familiar with your dashboard and understand key metrics',
      requiredForDay: false,
      points: 30,
      actionUrl: '/dashboard',
      estimatedMinutes: 3,
    },
  ],
  2: [
    {
      taskId: 'add-first-client',
      taskType: 'client',
      title: 'Add Your First Client',
      description: 'Create a client profile to start managing your relationships',
      requiredForDay: true,
      points: 150,
      actionUrl: '/clients',
      estimatedMinutes: 8,
    },
    {
      taskId: 'explore-ai-agents',
      taskType: 'exploration',
      title: 'Meet Your AI Assistants',
      description: 'Discover how Luca, Cadence, and other AI agents can help automate your work',
      requiredForDay: true,
      points: 75,
      actionUrl: '/ai-agents',
      estimatedMinutes: 5,
    },
    {
      taskId: 'setup-team',
      taskType: 'team',
      title: 'Invite Team Members',
      description: 'Add colleagues to collaborate on client work (optional)',
      requiredForDay: false,
      points: 100,
      actionUrl: '/teams',
      estimatedMinutes: 5,
    },
  ],
  3: [
    {
      taskId: 'create-first-invoice',
      taskType: 'invoice',
      title: 'Create Your First Invoice',
      description: 'Generate a professional invoice for a client',
      requiredForDay: true,
      points: 200,
      actionUrl: '/invoices',
      estimatedMinutes: 10,
    },
    {
      taskId: 'explore-workflows',
      taskType: 'exploration',
      title: 'Explore Workflow Automation',
      description: 'Learn how to automate repetitive tasks with workflows',
      requiredForDay: true,
      points: 100,
      actionUrl: '/workflows',
      estimatedMinutes: 8,
    },
    {
      taskId: 'upload-documents',
      taskType: 'documents',
      title: 'Upload Client Documents',
      description: 'Store important client files securely (optional)',
      requiredForDay: false,
      points: 50,
      actionUrl: '/documents',
      estimatedMinutes: 5,
    },
  ],
  // WEEK 1 (Days 4-7): Client Intake & Organization
  4: [
    {
      taskId: 'organize-with-tags',
      taskType: 'organization',
      title: 'Organize Clients with Tags',
      description: 'Create and apply tags to categorize your clients (e.g., tax, bookkeeping, advisory)',
      requiredForDay: true,
      points: 100,
      actionUrl: '/clients',
      estimatedMinutes: 8,
    },
    {
      taskId: 'setup-client-folders',
      taskType: 'documents',
      title: 'Set Up Client Folder Structure',
      description: 'Create organized folders for client document management',
      requiredForDay: true,
      points: 75,
      actionUrl: '/documents',
      estimatedMinutes: 10,
    },
    {
      taskId: 'customize-workspace',
      taskType: 'customization',
      title: 'Customize Your Workspace',
      description: 'Personalize your workspace settings and preferences (optional)',
      requiredForDay: false,
      points: 50,
      actionUrl: '/settings/workspace',
      estimatedMinutes: 5,
    },
  ],
  5: [
    {
      taskId: 'chat-with-luca',
      taskType: 'ai-agent',
      title: 'Chat with Luca AI',
      description: 'Ask Luca accounting questions and get instant answers',
      requiredForDay: true,
      points: 100,
      actionUrl: '/ai-agents/luca',
      estimatedMinutes: 10,
    },
    {
      taskId: 'setup-email-templates',
      taskType: 'communication',
      title: 'Create Email Templates',
      description: 'Set up reusable email templates for client communication',
      requiredForDay: true,
      points: 125,
      actionUrl: '/templates/emails',
      estimatedMinutes: 12,
    },
    {
      taskId: 'explore-marketplace',
      taskType: 'exploration',
      title: 'Browse Template Marketplace',
      description: 'Discover pre-built workflow templates and forms (optional)',
      requiredForDay: false,
      points: 50,
      actionUrl: '/marketplace',
      estimatedMinutes: 7,
    },
  ],
  6: [
    {
      taskId: 'create-client-portal',
      taskType: 'client',
      title: 'Set Up Client Portal Access',
      description: 'Enable client portal for secure document sharing and communication',
      requiredForDay: true,
      points: 150,
      actionUrl: '/clients',
      estimatedMinutes: 10,
    },
    {
      taskId: 'setup-notifications',
      taskType: 'settings',
      title: 'Configure Notifications',
      description: 'Choose when and how you receive alerts about client activities',
      requiredForDay: true,
      points: 75,
      actionUrl: '/settings/notifications',
      estimatedMinutes: 5,
    },
    {
      taskId: 'connect-email',
      taskType: 'integration',
      title: 'Connect Your Email Account',
      description: 'Integrate Gmail for automated email-to-task conversion (optional)',
      requiredForDay: false,
      points: 100,
      actionUrl: '/settings/integrations',
      estimatedMinutes: 8,
    },
  ],
  7: [
    {
      taskId: 'create-first-workflow',
      taskType: 'workflow',
      title: 'Build Your First Workflow',
      description: 'Create an automated workflow for client onboarding or tax prep',
      requiredForDay: true,
      points: 200,
      actionUrl: '/workflows/new',
      estimatedMinutes: 15,
    },
    {
      taskId: 'week1-review',
      taskType: 'milestone',
      title: 'Week 1 Milestone Review',
      description: 'Review your progress and client setup achievements',
      requiredForDay: true,
      points: 100,
      actionUrl: '/onboarding',
      estimatedMinutes: 5,
    },
    {
      taskId: 'invite-clients',
      taskType: 'client',
      title: 'Invite Clients to Portal',
      description: 'Send portal invitations to your clients (optional)',
      requiredForDay: false,
      points: 75,
      actionUrl: '/clients',
      estimatedMinutes: 7,
    },
  ],
  // WEEK 2 (Days 8-14): Bookkeeping & Transaction Management
  8: [
    {
      taskId: 'explore-projects',
      taskType: 'exploration',
      title: 'Explore Project Management',
      description: 'Learn how to track client engagements with projects',
      requiredForDay: true,
      points: 100,
      actionUrl: '/projects',
      estimatedMinutes: 10,
    },
    {
      taskId: 'create-first-project',
      taskType: 'project',
      title: 'Create Your First Project',
      description: 'Set up a project to track deliverables and milestones',
      requiredForDay: true,
      points: 150,
      actionUrl: '/projects/new',
      estimatedMinutes: 12,
    },
    {
      taskId: 'setup-time-tracking',
      taskType: 'time',
      title: 'Enable Time Tracking',
      description: 'Track billable hours on client work (optional)',
      requiredForDay: false,
      points: 75,
      actionUrl: '/settings/time',
      estimatedMinutes: 5,
    },
  ],
  9: [
    {
      taskId: 'use-cadence-agent',
      taskType: 'ai-agent',
      title: 'Build Workflow with Cadence',
      description: 'Use Cadence AI to create a workflow from conversation or document',
      requiredForDay: true,
      points: 175,
      actionUrl: '/ai-agents/cadence',
      estimatedMinutes: 15,
    },
    {
      taskId: 'assign-workflow',
      taskType: 'workflow',
      title: 'Assign Workflow to Client',
      description: 'Launch your first automated workflow assignment',
      requiredForDay: true,
      points: 125,
      actionUrl: '/workflows',
      estimatedMinutes: 8,
    },
    {
      taskId: 'explore-analytics',
      taskType: 'exploration',
      title: 'View Analytics Dashboard',
      description: 'Check your firm\'s performance metrics and insights (optional)',
      requiredForDay: false,
      points: 50,
      actionUrl: '/analytics',
      estimatedMinutes: 6,
    },
  ],
  10: [
    {
      taskId: 'create-service-plan',
      taskType: 'service',
      title: 'Create a Service Plan',
      description: 'Package your services with pricing and deliverables',
      requiredForDay: true,
      points: 200,
      actionUrl: '/services/new',
      estimatedMinutes: 15,
    },
    {
      taskId: 'configure-payment-gateway',
      taskType: 'billing',
      title: 'Configure Payment Gateway',
      description: 'Set up Stripe or Razorpay to accept client payments',
      requiredForDay: true,
      points: 150,
      actionUrl: '/settings/payments',
      estimatedMinutes: 10,
    },
    {
      taskId: 'customize-invoice-template',
      taskType: 'customization',
      title: 'Customize Invoice Template',
      description: 'Brand your invoices with logo and colors (optional)',
      requiredForDay: false,
      points: 75,
      actionUrl: '/settings/invoices',
      estimatedMinutes: 8,
    },
  ],
  11: [
    {
      taskId: 'use-forma-agent',
      taskType: 'ai-agent',
      title: 'Generate Form with Forma',
      description: 'Create a custom form using Forma AI agent',
      requiredForDay: true,
      points: 125,
      actionUrl: '/ai-agents/forma',
      estimatedMinutes: 10,
    },
    {
      taskId: 'send-client-organizer',
      taskType: 'forms',
      title: 'Send Tax Organizer to Client',
      description: 'Request client information using automated forms',
      requiredForDay: true,
      points: 150,
      actionUrl: '/forms',
      estimatedMinutes: 12,
    },
    {
      taskId: 'setup-automation-rules',
      taskType: 'automation',
      title: 'Configure Automation Rules',
      description: 'Set up conditional workflows based on client tags (optional)',
      requiredForDay: false,
      points: 100,
      actionUrl: '/workflows/automations',
      estimatedMinutes: 10,
    },
  ],
  12: [
    {
      taskId: 'use-echo-agent',
      taskType: 'ai-agent',
      title: 'Compose Message with Echo',
      description: 'Draft professional client communications using Echo AI',
      requiredForDay: true,
      points: 100,
      actionUrl: '/ai-agents/echo',
      estimatedMinutes: 8,
    },
    {
      taskId: 'create-message-template',
      taskType: 'communication',
      title: 'Create Message Templates',
      description: 'Set up reusable message templates for common scenarios',
      requiredForDay: true,
      points: 125,
      actionUrl: '/templates/messages',
      estimatedMinutes: 10,
    },
    {
      taskId: 'setup-team-roles',
      taskType: 'team',
      title: 'Configure Team Permissions',
      description: 'Define roles and access levels for team members (optional)',
      requiredForDay: false,
      points: 75,
      actionUrl: '/teams/roles',
      estimatedMinutes: 8,
    },
  ],
  13: [
    {
      taskId: 'use-scribe-agent',
      taskType: 'ai-agent',
      title: 'Design Email with Scribe',
      description: 'Create branded email templates using Scribe AI',
      requiredForDay: true,
      points: 125,
      actionUrl: '/ai-agents/scribe',
      estimatedMinutes: 10,
    },
    {
      taskId: 'track-client-tasks',
      taskType: 'tasks',
      title: 'Manage Client Tasks',
      description: 'Create and assign tasks within workflow assignments',
      requiredForDay: true,
      points: 100,
      actionUrl: '/workflows',
      estimatedMinutes: 10,
    },
    {
      taskId: 'explore-document-templates',
      taskType: 'exploration',
      title: 'Browse Document Templates',
      description: 'Discover pre-built engagement letters and contracts (optional)',
      requiredForDay: false,
      points: 50,
      actionUrl: '/marketplace/documents',
      estimatedMinutes: 5,
    },
  ],
  14: [
    {
      taskId: 'use-radar-agent',
      taskType: 'ai-agent',
      title: 'Monitor Activity with Radar',
      description: 'Track client interactions and workflow progress using Radar AI',
      requiredForDay: true,
      points: 100,
      actionUrl: '/ai-agents/radar',
      estimatedMinutes: 8,
    },
    {
      taskId: 'week2-review',
      taskType: 'milestone',
      title: 'Week 2 Milestone Review',
      description: 'Review your workflow automation and client engagement progress',
      requiredForDay: true,
      points: 150,
      actionUrl: '/onboarding',
      estimatedMinutes: 8,
    },
    {
      taskId: 'generate-client-report',
      taskType: 'reporting',
      title: 'Generate Client Report',
      description: 'Create a status report for client review (optional)',
      requiredForDay: false,
      points: 100,
      actionUrl: '/reports',
      estimatedMinutes: 10,
    },
  ],
  // WEEK 3 (Days 15-21): Compliance, Reporting & Advanced Features
  15: [
    {
      taskId: 'use-parity-agent',
      taskType: 'ai-agent',
      title: 'Get Compliance Help from Parity',
      description: 'Ask Parity AI about accounting standards and compliance requirements',
      requiredForDay: true,
      points: 125,
      actionUrl: '/ai-agents/parity',
      estimatedMinutes: 10,
    },
    {
      taskId: 'setup-document-signatures',
      taskType: 'documents',
      title: 'Enable Digital Signatures',
      description: 'Configure PKI digital signatures for tamper-proof documents',
      requiredForDay: true,
      points: 150,
      actionUrl: '/settings/signatures',
      estimatedMinutes: 12,
    },
    {
      taskId: 'explore-advanced-workflows',
      taskType: 'exploration',
      title: 'Explore Advanced Workflows',
      description: 'Discover multi-stage workflows with conditional logic (optional)',
      requiredForDay: false,
      points: 75,
      actionUrl: '/workflows/advanced',
      estimatedMinutes: 8,
    },
  ],
  16: [
    {
      taskId: 'use-relay-agent',
      taskType: 'ai-agent',
      title: 'Convert Email with Relay',
      description: 'Use Relay AI to automatically create tasks from client emails',
      requiredForDay: true,
      points: 125,
      actionUrl: '/ai-agents/relay',
      estimatedMinutes: 10,
    },
    {
      taskId: 'setup-recurring-workflows',
      taskType: 'automation',
      title: 'Schedule Recurring Workflows',
      description: 'Automate monthly/quarterly workflows for tax and compliance',
      requiredForDay: true,
      points: 175,
      actionUrl: '/workflows/recurring',
      estimatedMinutes: 15,
    },
    {
      taskId: 'customize-client-portal',
      taskType: 'customization',
      title: 'Brand Client Portal',
      description: 'Customize portal with your firm\'s branding (optional)',
      requiredForDay: false,
      points: 100,
      actionUrl: '/settings/portal',
      estimatedMinutes: 10,
    },
  ],
  17: [
    {
      taskId: 'use-omnispectra-agent',
      taskType: 'ai-agent',
      title: 'Track Status with OmniSpectra',
      description: 'Monitor real-time workflow status across all clients using OmniSpectra AI',
      requiredForDay: true,
      points: 100,
      actionUrl: '/ai-agents/omnispectra',
      estimatedMinutes: 8,
    },
    {
      taskId: 'analyze-workload',
      taskType: 'analytics',
      title: 'Review Team Workload Insights',
      description: 'Analyze team capacity and assignment distribution',
      requiredForDay: true,
      points: 125,
      actionUrl: '/analytics/workload',
      estimatedMinutes: 10,
    },
    {
      taskId: 'setup-backup-codes',
      taskType: 'security',
      title: 'Enable MFA Backup Codes',
      description: 'Set up multi-factor authentication for enhanced security (optional)',
      requiredForDay: false,
      points: 75,
      actionUrl: '/settings/security',
      estimatedMinutes: 5,
    },
  ],
  18: [
    {
      taskId: 'create-ai-agent',
      taskType: 'ai-agent',
      title: 'Build Custom AI Agent',
      description: 'Use Agent Foundry to create your own specialized AI assistant',
      requiredForDay: true,
      points: 250,
      actionUrl: '/foundry',
      estimatedMinutes: 20,
    },
    {
      taskId: 'publish-marketplace-template',
      taskType: 'marketplace',
      title: 'Publish Template to Marketplace',
      description: 'Share your workflow or form template with the Accute community',
      requiredForDay: true,
      points: 200,
      actionUrl: '/marketplace/publish',
      estimatedMinutes: 15,
    },
    {
      taskId: 'explore-subscription-addons',
      taskType: 'exploration',
      title: 'Explore Subscription Add-ons',
      description: 'Discover additional features and capacity upgrades (optional)',
      requiredForDay: false,
      points: 50,
      actionUrl: '/settings/subscription',
      estimatedMinutes: 5,
    },
  ],
  19: [
    {
      taskId: 'setup-mentions-collaboration',
      taskType: 'collaboration',
      title: 'Use @Mentions for Collaboration',
      description: 'Tag team members in chats and annotations for efficient collaboration',
      requiredForDay: true,
      points: 100,
      actionUrl: '/workflows',
      estimatedMinutes: 8,
    },
    {
      taskId: 'configure-auto-advance',
      taskType: 'automation',
      title: 'Set Up Auto-Advance Triggers',
      description: 'Configure event-driven workflow progression (payment received, document uploaded, etc.)',
      requiredForDay: true,
      points: 175,
      actionUrl: '/workflows/triggers',
      estimatedMinutes: 15,
    },
    {
      taskId: 'export-client-data',
      taskType: 'reporting',
      title: 'Export Client Data',
      description: 'Generate CSV/Excel exports for external analysis (optional)',
      requiredForDay: false,
      points: 75,
      actionUrl: '/clients/export',
      estimatedMinutes: 5,
    },
  ],
  20: [
    {
      taskId: 'review-all-agents',
      taskType: 'milestone',
      title: 'Review All 10 AI Agents',
      description: 'Revisit each AI agent and understand their specialized capabilities',
      requiredForDay: true,
      points: 150,
      actionUrl: '/ai-agents',
      estimatedMinutes: 15,
    },
    {
      taskId: 'optimize-workflows',
      taskType: 'optimization',
      title: 'Optimize Your Workflows',
      description: 'Review and refine your automated workflows for efficiency',
      requiredForDay: true,
      points: 125,
      actionUrl: '/workflows',
      estimatedMinutes: 12,
    },
    {
      taskId: 'setup-api-access',
      taskType: 'integration',
      title: 'Generate API Keys',
      description: 'Set up API access for third-party integrations (optional)',
      requiredForDay: false,
      points: 100,
      actionUrl: '/settings/api',
      estimatedMinutes: 8,
    },
  ],
  21: [
    {
      taskId: 'final-mastery-quiz',
      taskType: 'milestone',
      title: 'Complete Mastery Assessment',
      description: 'Demonstrate your understanding of Accute\'s key features and AI capabilities',
      requiredForDay: true,
      points: 300,
      actionUrl: '/onboarding/assessment',
      estimatedMinutes: 15,
    },
    {
      taskId: 'week3-review',
      taskType: 'milestone',
      title: 'Final Week Review & Celebration',
      description: 'Review your complete 21-day journey and achievements',
      requiredForDay: true,
      points: 200,
      actionUrl: '/onboarding/complete',
      estimatedMinutes: 10,
    },
    {
      taskId: 'join-community',
      taskType: 'community',
      title: 'Join Accute Community',
      description: 'Connect with other accounting professionals and share best practices (optional)',
      requiredForDay: false,
      points: 100,
      actionUrl: '/community',
      estimatedMinutes: 5,
    },
  ],
};

/**
 * Get task templates for a specific day
 */
export function getTasksForDay(day: number): OnboardingTaskTemplate[] {
  return ONBOARDING_TEMPLATES[day] || [];
}

/**
 * Check if day has tasks defined
 */
export function hasDayTemplates(day: number): boolean {
  return day in ONBOARDING_TEMPLATES && ONBOARDING_TEMPLATES[day].length > 0;
}

/**
 * Get total days with templates defined
 */
export function getTotalDaysWithTemplates(): number {
  return Object.keys(ONBOARDING_TEMPLATES).length;
}
