import { AgentMetadata } from './types/agent';

export const AGENT_REGISTRY: AgentMetadata[] = [
  {
    slug: 'luca',
    name: 'Luca',
    description: 'AI Accounting Expert - Your intelligent assistant for accounting, finance, and taxation queries',
    icon: 'Calculator',
    color: '#FF6B35',
    category: 'finance',
    hasSessionPersistence: false,
    requiresLLMConfig: true,
    supportsFileUpload: true,
    supportsWebSocket: true,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/luca', '/agents/luca'],
    primaryPath: '/ai-agents/luca',
    supportedFileTypes: ['pdf', 'docx', 'xlsx', 'csv', 'txt'],
    maxFileSize: 10 * 1024 * 1024,
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    slug: 'cadence',
    name: 'Cadence',
    description: 'Tax Compliance Specialist - Expert guidance on tax regulations and compliance',
    icon: 'FileText',
    color: '#4ECDC4',
    category: 'compliance',
    hasSessionPersistence: true,
    requiresLLMConfig: true,
    supportsFileUpload: true,
    supportsWebSocket: true,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/cadence', '/agents/cadence'],
    primaryPath: '/ai-agents/cadence',
    supportedFileTypes: ['pdf', 'docx', 'xlsx', 'csv', 'txt'],
    maxFileSize: 10 * 1024 * 1024,
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    slug: 'parity',
    name: 'Parity',
    description: 'Financial Audit Agent - Comprehensive audit and reconciliation assistance',
    icon: 'Scale',
    color: '#95E1D3',
    category: 'finance',
    hasSessionPersistence: false,
    requiresLLMConfig: true,
    supportsFileUpload: true,
    supportsWebSocket: true,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/parity', '/agents/parity'],
    primaryPath: '/ai-agents/parity',
    supportedFileTypes: ['pdf', 'docx', 'xlsx', 'csv', 'txt'],
    maxFileSize: 10 * 1024 * 1024,
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    slug: 'forma',
    name: 'Forma',
    description: 'Document Processing Specialist - Intelligent form and document analysis',
    icon: 'FileSearch',
    color: '#F38181',
    category: 'automation',
    hasSessionPersistence: false,
    requiresLLMConfig: true,
    supportsFileUpload: true,
    supportsWebSocket: true,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/forma', '/agents/forma'],
    primaryPath: '/ai-agents/forma',
    supportedFileTypes: ['pdf', 'docx', 'xlsx', 'csv', 'txt'],
    maxFileSize: 10 * 1024 * 1024,
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    slug: 'echo',
    name: 'Echo',
    description: 'Communication Agent - Client communication and engagement specialist',
    icon: 'MessageSquare',
    color: '#AA96DA',
    category: 'communication',
    hasSessionPersistence: false,
    requiresLLMConfig: true,
    supportsFileUpload: true,
    supportsWebSocket: true,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/echo', '/agents/echo'],
    primaryPath: '/ai-agents/echo',
    supportedFileTypes: ['pdf', 'docx', 'txt'],
    maxFileSize: 10 * 1024 * 1024,
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    slug: 'relay',
    name: 'Relay',
    description: 'Workflow Automation Expert - Streamline your accounting processes',
    icon: 'Workflow',
    color: '#FCBAD3',
    category: 'automation',
    hasSessionPersistence: false,
    requiresLLMConfig: true,
    supportsFileUpload: false,
    supportsWebSocket: true,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/relay', '/agents/relay'],
    primaryPath: '/ai-agents/relay',
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    slug: 'scribe',
    name: 'Scribe',
    description: 'Meeting Notes & Transcription - Capture and summarize important discussions',
    icon: 'BookOpen',
    color: '#A8D8EA',
    category: 'communication',
    hasSessionPersistence: false,
    requiresLLMConfig: true,
    supportsFileUpload: true,
    supportsWebSocket: true,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/scribe', '/agents/scribe'],
    primaryPath: '/ai-agents/scribe',
    supportedFileTypes: ['pdf', 'docx', 'txt'],
    maxFileSize: 10 * 1024 * 1024,
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    slug: 'radar',
    name: 'Radar',
    description: 'Risk & Compliance Monitoring - Proactive risk detection and compliance tracking',
    icon: 'Activity',
    color: '#FFD93D',
    category: 'compliance',
    hasSessionPersistence: false,
    requiresLLMConfig: true,
    supportsFileUpload: true,
    supportsWebSocket: false,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/radar', '/agents/radar'],
    primaryPath: '/ai-agents/radar',
    supportedFileTypes: ['pdf', 'xlsx', 'csv'],
    maxFileSize: 10 * 1024 * 1024,
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    slug: 'omnispectra',
    name: 'OmniSpectra',
    description: 'Multi-Channel Analytics - Comprehensive business intelligence and insights',
    icon: 'BarChart',
    color: '#6BCF7F',
    category: 'analytics',
    hasSessionPersistence: false,
    requiresLLMConfig: true,
    supportsFileUpload: true,
    supportsWebSocket: false,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/omnispectra', '/agents/omnispectra'],
    primaryPath: '/ai-agents/omnispectra',
    supportedFileTypes: ['pdf', 'xlsx', 'csv'],
    maxFileSize: 10 * 1024 * 1024,
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
  {
    slug: 'lynk',
    name: 'Lynk',
    description: 'Integration Specialist - Connect and synchronize your accounting tools',
    icon: 'Link',
    color: '#C96480',
    category: 'automation',
    hasSessionPersistence: false,
    requiresLLMConfig: true,
    supportsFileUpload: false,
    supportsWebSocket: true,
    websocketTopic: '/ws/ai-stream',
    routePaths: ['/ai-agents/lynk', '/agents/lynk'],
    primaryPath: '/ai-agents/lynk',
    version: '1.0.0',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-11-16'),
  },
];

export function getAgentBySlug(slug: string): AgentMetadata | undefined {
  return AGENT_REGISTRY.find(agent => agent.slug === slug);
}

export function getAllAgentSlugs(): string[] {
  return AGENT_REGISTRY.map(agent => agent.slug);
}

export function getAgentsByCategory(category: AgentMetadata['category']): AgentMetadata[] {
  return AGENT_REGISTRY.filter(agent => agent.category === category);
}

export function getWebSocketEnabledAgents(): AgentMetadata[] {
  return AGENT_REGISTRY.filter(agent => agent.supportsWebSocket);
}
